/**
 * The service worker, generated after the build (docs/12 → M1: app shell
 * precache; docs/10 → models cached by the service worker).
 *
 * - Precache: the home and offline pages and every script, style and font
 *   they reference, so the site opens without a network once visited.
 * - Pages: network first, then the cached copy, then /offline.
 * - /_next/static/*: cache first (content-hashed, immutable).
 * - Models and WASM (/models/* or the MODELS_BASE_URL origin): cache first in
 *   a separate, unversioned cache, so a 115 MB model downloads once.
 * Old versions' caches are deleted on activate; the models cache is kept.
 */
import { createHash } from 'node:crypto';

/** Same-origin static assets referenced by an HTML page. */
export function assetsIn(html: string): string[] {
  const found = new Set<string>();
  for (const match of html.matchAll(/(?:src|href)="(\/_next\/static\/[^"?#]+)"/g)) {
    if (match[1]) found.add(match[1]);
  }
  return [...found];
}

export function serviceWorker({
  precache,
  modelsOrigin,
}: {
  precache: string[];
  modelsOrigin: string | null;
}): string {
  const list = [...new Set(precache)].sort();
  const version = createHash('sha256').update(list.join('\n')).digest('hex').slice(0, 12);
  return `// Generated by apps/web/scripts/postbuild.ts. Do not edit.
const VERSION = ${JSON.stringify(version)};
const SHELL = 'etb-shell-' + VERSION;
const MODELS = 'etb-models';
const MODELS_ORIGIN = ${JSON.stringify(modelsOrigin)};
const PRECACHE = ${JSON.stringify(list)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(SHELL)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key.startsWith('etb-shell-') && key !== SHELL).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

async function cacheFirst(request, name) {
  const cache = await caches.open(name);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response.ok) await cache.put(request, response.clone());
  return response;
}

async function networkFirst(request) {
  const cache = await caches.open(SHELL);
  try {
    const response = await fetch(request);
    if (response.ok) await cache.put(request, response.clone());
    return response;
  } catch (error) {
    return (await cache.match(request)) || (await cache.match('/offline')) || Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    if (MODELS_ORIGIN && url.origin === MODELS_ORIGIN) event.respondWith(cacheFirst(request, MODELS));
    return;
  }
  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
  } else if (url.pathname.startsWith('/models/')) {
    event.respondWith(cacheFirst(request, MODELS));
  } else if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith(cacheFirst(request, SHELL));
  }
});
`;
}
