/**
 * The service worker, generated after the build (docs/12 → M1: app shell
 * precache; docs/10 → models cached by the service worker).
 *
 * - Precache: the home and offline pages and every script, style and font
 *   they reference, so the site opens without a network once visited.
 * - Pages: network first, then the cached copy, then /offline.
 * - /_next/static/*: cache first (content-hashed, immutable).
 * - Models and WASM (/models/* or the MODELS_BASE_URL origin): cache first in
 *   a separate, unversioned cache, so a 115 MB model downloads once.
 * - Android's share sheet (the manifest's share_target) POSTs files to
 *   /share. The worker holds them in the `etb-shared` cache, on this device
 *   only, and sends the browser to /share, which reads them, deletes them at
 *   once and hands them to the tool picked (docs/01 → Mobile).
 * Old versions' caches are deleted on activate; the models cache is kept.
 *
 * The server build (`shell: false`, served by src/app/sw.js/route.server.ts)
 * keeps only the share target and the models cache: no precache and no page
 * or script caching, so a signed-in page always comes from the network.
 */
import { createHash } from 'node:crypto';

/** Same-origin static assets referenced by an HTML page. */
export function assetsIn(html: string): string[] {
  const found = new Set<string>();
  for (const match of html.matchAll(/(?:src|href)="(\/_next\/static\/[^"?#]+)"/g)) {
    if (match[1]) found.add(match[1]);
  }
  return [...found];
}

/** Pages: network first, then the cached copy, then /offline (the app shell only). */
const NETWORK_FIRST = `async function networkFirst(request) {
  const cache = await caches.open(SHELL);
  try {
    const response = await fetch(request);
    if (response.ok) await cache.put(request, response.clone());
    return response;
  } catch (error) {
    return (await cache.match(request)) || (await cache.match('/offline')) || Response.error();
  }
}

`;

/** The app shell's own requests: pages network first, hashed scripts cache first. */
const SHELL_ROUTES = `  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
  } else if (url.pathname.startsWith('/_next/static/')) {
    // Turbopack starts every worker from one bootstrap script and names its
    // chunks in the URL fragment (#params=...). The Cache API ignores
    // fragments, so the stored response would carry the first worker's URL
    // and hand that worker's chunks to the next one. A copy without the
    // stored URL keeps this request's fragment.
    event.respondWith(
      url.hash
        ? cacheFirst(request, SHELL).then(
            (response) =>
              new Response(response.body, {
                status: response.status,
                statusText: response.statusText,
                headers: response.headers,
              }),
          )
        : cacheFirst(request, SHELL),
    );
  }
`;

export function serviceWorker({
  precache,
  modelsOrigin,
  shell = true,
}: {
  precache: string[];
  modelsOrigin: string | null;
  /** The app shell: precache, pages offline, hashed scripts. False for the server build. */
  shell?: boolean;
}): string {
  const list = shell ? [...new Set(precache)].sort() : [];
  const version = createHash('sha256').update(list.join('\n')).digest('hex').slice(0, 12);
  const install = shell
    ? `self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(SHELL)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});`
    : `self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting());
});`;
  return `// Generated by apps/web/scripts/${shell ? 'postbuild.ts' : 'sw.ts'}. Do not edit.
const VERSION = ${JSON.stringify(version)};
const SHELL = 'etb-shell-' + VERSION;
const MODELS = 'etb-models';
const SHARED = 'etb-shared';
/** At most this many shared files are kept for the /share page. */
const SHARE_LIMIT = 50;
const MODELS_ORIGIN = ${JSON.stringify(modelsOrigin)};
const PRECACHE = ${JSON.stringify(list)};

${install}

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key.startsWith('etb-shell-') && key !== SHELL).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

async function cacheFirst(request, name) {
  const cache = await caches.open(name);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response.ok) await cache.put(request, response.clone());
  return response;
}

${shell ? NETWORK_FIRST : ''}/** Files shared from another app: kept until /share reads them, then the page takes over. */
async function receiveShare(request) {
  let files = [];
  try {
    const form = await request.formData();
    files = form.getAll('files').filter((item) => typeof item === 'object' && item !== null);
  } catch (error) {
    files = [];
  }
  const cache = await caches.open(SHARED);
  for (const key of await cache.keys()) await cache.delete(key);
  const kept = files.slice(0, SHARE_LIMIT);
  await Promise.all(
    kept.map((file, index) =>
      cache.put(
        '/share/file/' + index,
        new Response(file, {
          headers: {
            'Content-Type': file.type || 'application/octet-stream',
            'X-File-Name': encodeURIComponent(file.name || 'shared-file'),
            'X-Shared-At': String(Date.now()),
          },
        }),
      ),
    ),
  );
  return Response.redirect(
    self.location.origin + '/share?files=' + kept.length + (files.length > kept.length ? '&more=1' : ''),
    303,
  );
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method === 'POST' && url.origin === self.location.origin && url.pathname === '/share') {
    event.respondWith(receiveShare(request));
    return;
  }
  if (request.method !== 'GET') return;
  if (url.origin !== self.location.origin) {
    if (MODELS_ORIGIN && url.origin === MODELS_ORIGIN) event.respondWith(cacheFirst(request, MODELS));
    return;
  }
  if (url.pathname.startsWith('/models/')) {
    event.respondWith(cacheFirst(request, MODELS));
    return;
  }
${shell ? SHELL_ROUTES : ''}});
`;
}
