/**
 * Ids of the tools that have a view in src/tools. A plain module, so server
 * code can read it (exports of the 'use client' map are client references).
 * The map in ./index.tsx is typed against this list, so the two can't drift.
 */
export const TOOL_IDS = [
  'add-text-to-image',
  'aspect-ratio-calculator',
  'audio-channels',
  'audio-converter',
  'batch-rename',
  'bitrate-calculator',
  'blur-image',
  'bpm-key-finder',
  'change-pitch',
  'burn-subtitles',
  'color-converter',
  'color-palette-from-image',
  'color-picker-from-image',
  'compress-image',
  'compress-video',
  'contrast-checker',
  'crop-image',
  'dpi-calculator',
  'draw-on-image',
  'exif-remover',
  'extract-audio',
  'extract-frames',
  'file-checksum',
  'fade-audio',
  'gif-to-mp4',
  'gradient-generator',
  'image-converter',
  'loop-video',
  'loudness-meter',
  'lut-preview',
  'merge-audio',
  'merge-videos',
  'mute-video',
  'normalize-audio',
  'photo-editor',
  'qr-code-generator',
  'remove-background',
  'remove-silence',
  'replace-audio',
  'resize-image',
  'resize-video',
  'reverse-audio',
  'reverse-video',
  'rotate-image',
  'rotate-video',
  'shutter-angle-calculator',
  'social-media-image-resizer',
  'split-audio',
  'split-image',
  'storage-calculator',
  'subtitle-converter',
  'subtitle-shift',
  'timecode-calculator',
  'trim-audio',
  'trim-video',
  'vfr-to-cfr',
  'video-converter',
  'video-info',
  'video-speed',
  'video-to-gif',
  'watermark-image',
] as const;

export type ToolId = (typeof TOOL_IDS)[number];

export function hasView(id: string): id is ToolId {
  return (TOOL_IDS as readonly string[]).includes(id);
}
